import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { TypegenManifest } from '@lumibase/sdk';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { DEFAULT_OUT, renderTypes, typesCommand } from './types.js';
import { parseArgs } from '../utils/args.js';

const MANIFEST: TypegenManifest = {
  version: 1,
  site: 'site_abc',
  collections: [
    {
      name: 'articles',
      primaryKey: 'id',
      fields: [
        { name: 'id', type: 'string', required: true, nullable: false, primaryKey: true },
        { name: 'title', type: 'string', required: true, nullable: false },
      ],
    },
  ],
};

const ENV = {
  LUMIBASE_URL: 'http://localhost:1989',
  LUMIBASE_SITE_ID: 'site_abc',
  LUMIBASE_TOKEN: 'tok_abc',
};

const created: string[] = [];

function tempDir(): string {
  const dir = mkdtempSync(join(tmpdir(), 'lumibase-types-'));
  created.push(dir);
  return dir;
}

/** A fetch stand-in that answers the typegen endpoint and records the URL hit. */
function fakeFetch(manifest: TypegenManifest = MANIFEST) {
  const calls: string[] = [];
  const fetcher = vi.fn(async (input: unknown) => {
    calls.push(String(input));
    return new Response(JSON.stringify({ data: manifest }), {
      status: 200,
      headers: { 'content-type': 'application/json' },
    });
  }) as unknown as typeof fetch;

  return { fetcher, calls };
}

afterEach(() => {
  while (created.length > 0) {
    const dir = created.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

describe('renderTypes', () => {
  it('prefixes a generated-file banner', () => {
    expect(renderTypes(MANIFEST, true)).toMatch(/^\/\/ Generated by `lumibase types`/);
  });

  it('is deterministic — no timestamp or host in the output', () => {
    const first = renderTypes(MANIFEST, true);
    const second = renderTypes(MANIFEST, true);

    expect(first).toBe(second);
    expect(first).not.toContain('site_abc');
    expect(first).toMatch(/interface Articles/);
  });

  it('ends with exactly one trailing newline', () => {
    const output = renderTypes(MANIFEST, true);
    expect(output.endsWith('\n')).toBe(true);
    expect(output.endsWith('\n\n')).toBe(false);
  });
});

describe('typesCommand', () => {
  it('writes the default output file and reports the collection count', async () => {
    const cwd = tempDir();
    const { fetcher, calls } = fakeFetch();

    const code = await typesCommand(parseArgs(['types']), {
      cwd,
      env: ENV,
      request: { fetcher },
    });

    expect(code).toBe(0);
    expect(calls[0]).toContain('/api/v1/typegen/schema');
    expect(readFileSync(join(cwd, DEFAULT_OUT), 'utf8')).toContain('interface Articles');
  });

  it('honours --out, including nested directories', async () => {
    const cwd = tempDir();
    const { fetcher } = fakeFetch();

    await typesCommand(parseArgs(['types', '--out', 'src/generated/lumi.d.ts']), {
      cwd,
      env: ENV,
      request: { fetcher },
    });

    expect(existsSync(join(cwd, 'src/generated/lumi.d.ts'))).toBe(true);
  });

  it('forwards --include and --exclude as query parameters', async () => {
    const cwd = tempDir();
    const { fetcher, calls } = fakeFetch();

    await typesCommand(parseArgs(['types', '--include', 'articles, authors', '--exclude', 'logs']), {
      cwd,
      env: ENV,
      request: { fetcher },
    });

    const url = new URL(String(calls[0]));
    expect(url.searchParams.get('include')).toBe('articles,authors');
    expect(url.searchParams.get('exclude')).toBe('logs');
  });

  it('--check passes when the committed file matches', async () => {
    const cwd = tempDir();
    writeFileSync(join(cwd, DEFAULT_OUT), renderTypes(MANIFEST, true), 'utf8');
    const { fetcher } = fakeFetch();

    await expect(
      typesCommand(parseArgs(['types', '--check']), { cwd, env: ENV, request: { fetcher } }),
    ).resolves.toBe(0);
  });

  it('--check fails when the committed file is stale', async () => {
    const cwd = tempDir();
    writeFileSync(join(cwd, DEFAULT_OUT), '// stale\n', 'utf8');
    const { fetcher } = fakeFetch();

    await expect(
      typesCommand(parseArgs(['types', '--check']), { cwd, env: ENV, request: { fetcher } }),
    ).rejects.toThrow(/out of date/);
  });

  it('--check fails when the file is missing entirely', async () => {
    const { fetcher } = fakeFetch();

    await expect(
      typesCommand(parseArgs(['types', '--check']), {
        cwd: tempDir(),
        env: ENV,
        request: { fetcher },
      }),
    ).rejects.toThrow(/does not exist/);
  });

  it('--check never writes the file', async () => {
    const cwd = tempDir();
    const { fetcher } = fakeFetch();

    await typesCommand(parseArgs(['types', '--check']), {
      cwd,
      env: ENV,
      request: { fetcher },
    }).catch(() => undefined);

    expect(existsSync(join(cwd, DEFAULT_OUT))).toBe(false);
  });

  it('fails with a readable message when the connection is not configured', async () => {
    await expect(
      typesCommand(parseArgs(['types']), { cwd: tempDir(), env: {} }),
    ).rejects.toThrow(/Missing connection settings/);
  });

  it('surfaces a 401 as an authorization problem', async () => {
    const fetcher = vi.fn(async () => new Response('{}', { status: 401 })) as unknown as typeof fetch;

    await expect(
      typesCommand(parseArgs(['types']), { cwd: tempDir(), env: ENV, request: { fetcher } }),
    ).rejects.toThrow(/Unauthorized \(401\)/);
  });

  it('rejects a payload that is not a manifest', async () => {
    const fetcher = vi.fn(
      async () => new Response(JSON.stringify({ data: { nope: true } }), { status: 200 }),
    ) as unknown as typeof fetch;

    await expect(
      typesCommand(parseArgs(['types']), { cwd: tempDir(), env: ENV, request: { fetcher } }),
    ).rejects.toThrow(/unexpected payload/);
  });
});
