import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import process from 'node:process';
import { generateTypes, type TypegenManifest } from '@lumibase/sdk';
import { fetchTypegenManifest, type RequestOptions } from '../api.js';
import { requireConnection, resolveConfig } from '../config.js';
import { CliError } from '../errors.js';
import { boolFlag, stringFlag, type ParsedArgs } from '../utils/args.js';
import { log } from '../utils/log.js';

export const DEFAULT_OUT = 'lumibase-types.d.ts';

/**
 * The generated file imports `ID` / `Locale` / `Brand` from here. `lumibase`
 * re-exports the SDK, and it is the package a project running this CLI has
 * installed — so it is the default, and `@lumibase/sdk` is the opt-in for
 * projects that depend on the SDK directly (`--import-from @lumibase/sdk`).
 */
export const DEFAULT_IMPORT_FROM = 'lumibase';

export interface RenderTypesOptions {
  branded: boolean;
  importFrom?: string;
}

/**
 * The banner deliberately carries no site id, host, or timestamp: `--check`
 * runs in CI against a different instance than the developer used, and any
 * environment-specific header would fail the check for no real reason.
 */
const BANNER = [
  '// Generated by `lumibase types` — do not edit by hand.',
  '// Re-run the command after changing collections or fields.',
].join('\n');

export function renderTypes(manifest: TypegenManifest, options: RenderTypesOptions): string {
  const { branded, importFrom = DEFAULT_IMPORT_FROM } = options;
  const body = generateTypes(manifest, { format: 'single', branded, importSource: importFrom });
  return `${BANNER}\n\n${body.trimEnd()}\n`;
}

function splitList(value: string | undefined): string[] | undefined {
  if (!value) return undefined;
  const items = value
    .split(',')
    .map((entry) => entry.trim())
    .filter(Boolean);
  return items.length > 0 ? items : undefined;
}

export interface TypesCommandOptions {
  cwd?: string;
  env?: NodeJS.ProcessEnv;
  request?: RequestOptions;
}

export async function typesCommand(
  args: ParsedArgs,
  options: TypesCommandOptions = {},
): Promise<number> {
  const cwd = options.cwd ?? process.cwd();
  const config = resolveConfig(args, { cwd, env: options.env });
  requireConnection(config);

  const check = boolFlag(args, 'check');
  const toStdout = boolFlag(args, 'stdout');
  const branded = boolFlag(args, 'no-branded') ? false : (config.typegen.branded ?? true);
  const importFrom =
    stringFlag(args, 'import-from') ?? config.typegen.importFrom ?? DEFAULT_IMPORT_FROM;

  const outPath = resolve(
    cwd,
    stringFlag(args, 'out') ?? config.typegen.out ?? DEFAULT_OUT,
  );

  const manifest = await fetchTypegenManifest(
    { url: config.url, siteId: config.siteId, token: config.token },
    {
      include: splitList(stringFlag(args, 'include')) ?? config.typegen.include,
      exclude: splitList(stringFlag(args, 'exclude')) ?? config.typegen.exclude,
    },
    options.request,
  );

  const generated = renderTypes(manifest, { branded, importFrom });
  const collectionCount = manifest.collections.length;

  if (toStdout) {
    process.stdout.write(generated);
    return 0;
  }

  const displayPath = relative(cwd, outPath) || outPath;
  const existing = existsSync(outPath) ? readFileSync(outPath, 'utf8') : undefined;

  if (check) {
    if (existing === undefined) {
      throw new CliError(
        `${displayPath} does not exist.`,
        'Run `lumibase types` and commit the result.',
      );
    }
    if (existing !== generated) {
      throw new CliError(
        `${displayPath} is out of date with the live schema.`,
        'Run `lumibase types` and commit the result.',
      );
    }
    log.success(`${displayPath} is up to date (${collectionCount} collections).`);
    return 0;
  }

  if (existing === generated) {
    log.success(`${displayPath} already up to date (${collectionCount} collections).`);
    return 0;
  }

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, generated, 'utf8');

  log.success(`Wrote ${displayPath} — ${collectionCount} collections.`);
  log.dim(`  Generated types import from ${importFrom} — install it in this project.`);

  return 0;
}
