/**
 * AI Flow config generator — produces a deployment {@link EnvironmentConfig}
 * for a given CDC approach and deployment target (ClickHouse CDC —
 * task 11.1; design "AI Flow Engine" §5 and "Deployment Topology",
 * Requirements 7.1, 7.2).
 *
 * The AI Flow Engine deploys the CDC system across LumiBase's dual-runtime
 * architecture, so a deployment is described by two axes:
 *
 *   - **approach** ({@link CdcConnectorType}) — which replication strategy
 *     the pipeline uses (`debezium_kafka`, `materialized_engine`, or
 *     `airbyte`). This selects the approach-specific environment variables
 *     and stateful services.
 *   - **target** ({@link DeploymentTarget}) — where the components run. This
 *     scopes *which* components are part of this deployment:
 *       - `docker_compose` (or managed services) hosts the **full stateful
 *         stack** for the approach — Kafka_Broker, Debezium_Connector,
 *         ClickHouse_Sink, Materialized_Engine, Airbyte_Connector (only the
 *         subset relevant to the approach). These require long-lived TCP
 *         connections, persistent buffers, and replication-slot ownership.
 *       - `cloudflare_workers` hosts **only the lightweight edge
 *         components** — the CDC API/control-plane endpoints and the
 *         Cache_Invalidator. A Workers deployment NEVER includes stateful
 *         connectors, the Kafka message bus, or replication engines; it
 *         always depends on a companion `docker_compose`/managed-services
 *         deployment for the stateful stack, reached over HTTPS.
 *
 * This module is **pure**: {@link generateConfig} performs no I/O and holds
 * no state. It is a referentially-transparent mapping from
 * `(approach, target)` to an {@link EnvironmentConfig}, so task 11.5
 * (Property 17 — every required variable is present for each approach +
 * target combination) can exercise it deterministically.
 *
 * Downstream consumers:
 *   - task 11.2 (`env-validator.ts`) validates submitted values against the
 *     {@link EnvVarDefinition.validation} rules surfaced here.
 *   - task 11.3 (`deployment-orchestrator.ts`) provisions the
 *     {@link EnvironmentConfig.services} listed here.
 *
 * Validates: Requirements 7.1, 7.2
 */

import type { CdcConnectorType } from '../connectors/types';

// ── target axis (design "Deployment Topology" / §5) ─────────────────────

/**
 * Where a CDC deployment's components run.
 *
 *   - `'docker_compose'`   → full stateful stack for the approach (Kafka,
 *     Debezium, ClickHouse, Materialized Engine, Airbyte), via Docker
 *     Compose containers on a shared network or external managed services
 *     (Confluent Cloud / ClickHouse Cloud / Airbyte Cloud).
 *   - `'cloudflare_workers'` → edge components ONLY (CDC API/control-plane
 *     endpoints + Cache_Invalidator). Cannot host stateful connectors, the
 *     message bus, or replication engines.
 */
export type DeploymentTarget = 'docker_compose' | 'cloudflare_workers';

// ── environment variable model (task 11.1) ──────────────────────────────

/**
 * Environment-variable key naming rule, kept in sync with the `key` regex
 * of `EnvVarSchema` in `packages/shared/src/schemas/cdc.ts`
 * (`/^[A-Z_][A-Z0-9_]*$/`). Every {@link EnvVarDefinition.key} generated by
 * this module conforms to this pattern so generated configs round-trip
 * cleanly through that shared schema.
 */
export const ENV_VAR_KEY_PATTERN = /^[A-Z_][A-Z0-9_]*$/;

/**
 * A machine-checkable validation rule for an environment variable value,
 * plus a human-readable description of the constraint. Task 11.2's
 * env-validator uses these fields to identify invalid values and report the
 * specific violated rule (Req 7.4, 7.5).
 *
 * Fields are additive — a definition may combine, for example, a `pattern`
 * with a human-readable `rule`. All fields except `rule` are optional.
 */
export interface EnvVarValidation {
  /** Human-readable description of the constraint (always present). */
  readonly rule: string;

  /**
   * Optional regular-expression source (string form) the value must match
   * in full. Stored as a string so the definition stays serialisable.
   */
  readonly pattern?: string;

  /** Optional set of allowed values (for enumerated variables). */
  readonly enum?: readonly string[];

  /**
   * Optional inclusive lower bound. Interpreted as a numeric minimum for
   * integer variables, or a minimum length for string variables.
   */
  readonly min?: number;

  /**
   * Optional inclusive upper bound. Interpreted as a numeric maximum for
   * integer variables, or a maximum length for string variables.
   */
  readonly max?: number;
}

/**
 * Definition of a single environment variable required (or optional) for a
 * deployment. Carries everything the documentation (task 15.1), the
 * env-validator (task 11.2), and the deployment orchestrator (task 11.3)
 * need: the key, a human-readable description, an optional default, whether
 * it is required, and the validation rule its value must satisfy.
 */
export interface EnvVarDefinition {
  /** UPPER_SNAKE_CASE variable name (matches {@link ENV_VAR_KEY_PATTERN}). */
  readonly key: string;

  /** Human-readable description of what the variable controls. */
  readonly description: string;

  /**
   * Sensible default value, when one exists. Absent (`undefined`) when the
   * operator MUST supply a value (e.g. connection strings, secrets).
   */
  readonly default?: string;

  /** Whether a value MUST be present for the deployment to be valid. */
  readonly required: boolean;

  /** Validation rule the value must satisfy. */
  readonly validation: EnvVarValidation;
}

// ── service model (task 11.1) ───────────────────────────────────────────

/**
 * Definition of a single service that is part of a deployment. Used by the
 * deployment orchestrator (task 11.3) to provision and health-check each
 * component, and by the documentation generator (task 15.1).
 */
export interface ServiceDefinition {
  /** Canonical service identifier, e.g. `'kafka_broker'`. */
  readonly name: string;

  /** Human-readable display name, e.g. `'Kafka Broker'`. */
  readonly displayName: string;

  /** Short description of the service's role in the pipeline. */
  readonly description: string;

  /**
   * Whether this is a **stateful** stack component (requires long-lived
   * connections / persistent storage / replication-slot ownership) as
   * opposed to a lightweight **edge** component. Stateful services only
   * appear in `docker_compose` deployments; edge services only appear in
   * `cloudflare_workers` deployments.
   */
  readonly stateful: boolean;

  /**
   * Container image (with tag) for `docker_compose` targets. Absent for
   * edge components (which run as Cloudflare Workers) and for logical
   * services that run inside another container (e.g. the Materialized
   * Engine runs inside ClickHouse).
   */
  readonly image?: string;

  /** Ports the service exposes on the shared network (docker_compose). */
  readonly ports?: readonly number[];

  /** Names of other services this service depends on (start ordering). */
  readonly dependsOn?: readonly string[];
}

// ── environment config (design §5) ──────────────────────────────────────

/**
 * Complete deployment configuration for one `(approach, target)`
 * combination — the output of {@link generateConfig}. Mirrors the
 * `EnvironmentConfig` interface in the design's "AI Flow Engine" section.
 */
export interface EnvironmentConfig {
  /** The CDC replication approach this config targets. */
  readonly approach: CdcConnectorType;

  /** Where the components in this config run. */
  readonly target: DeploymentTarget;

  /** All environment variables (required and optional) for the deployment. */
  readonly variables: readonly EnvVarDefinition[];

  /** The services provisioned by this deployment, scoped by target. */
  readonly services: readonly ServiceDefinition[];
}

// ── reusable validation builders ────────────────────────────────────────

/** A non-empty free-form string value. */
const NON_EMPTY: EnvVarValidation = {
  rule: 'Must be a non-empty string',
  min: 1,
};

/** A value that must be a connection URL with one of the given schemes. */
function urlValidation(schemes: readonly string[], note?: string): EnvVarValidation {
  const alternation = schemes.length === 1 ? schemes[0] : `(?:${schemes.join('|')})`;
  const schemeList = schemes.map((s) => `${s}://`).join(' or ');
  return {
    rule: `Must be a valid ${schemeList} connection URL${note ? ` (${note})` : ''}`,
    pattern: `^${alternation}:\\/\\/.+`,
  };
}

/** An integer value constrained to the inclusive range [min, max]. */
function intRangeValidation(min: number, max: number): EnvVarValidation {
  return {
    rule: `Must be an integer between ${min} and ${max} (inclusive)`,
    pattern: '^[0-9]+$',
    min,
    max,
  };
}

/** A positive integer value (≥ 1) with no explicit upper bound. */
function positiveIntValidation(): EnvVarValidation {
  return {
    rule: 'Must be a positive integer (≥ 1)',
    pattern: '^[1-9][0-9]*$',
    min: 1,
  };
}

/** A value restricted to a fixed set of choices. */
function enumValidation(values: readonly string[]): EnvVarValidation {
  return {
    rule: `Must be one of: ${values.join(', ')}`,
    enum: values,
  };
}

// ── service catalog (design "Deployment Topology") ──────────────────────

/** ClickHouse sink — the replication destination shared by all approaches. */
const CLICKHOUSE_SINK: ServiceDefinition = {
  name: 'clickhouse_sink',
  displayName: 'ClickHouse Sink',
  description: 'ClickHouse server that receives replicated data from the CDC pipeline.',
  stateful: true,
  image: 'clickhouse/clickhouse-server:24.3',
  ports: [8123, 9000],
};

/** Stateful services that make up the `docker_compose` stack, by approach. */
const STATEFUL_SERVICES_BY_APPROACH: Readonly<Record<CdcConnectorType, readonly ServiceDefinition[]>> = {
  // Debezium reads the WAL and publishes to Kafka; ClickHouse ingests via
  // the Kafka table engine (Req 2.1, 7.3).
  debezium_kafka: [
    {
      name: 'kafka_broker',
      displayName: 'Kafka Broker',
      description: 'Message bus that buffers and partitions Debezium change events by table.',
      stateful: true,
      image: 'confluentinc/cp-kafka:7.6.0',
      ports: [9092],
    },
    {
      name: 'debezium_connector',
      displayName: 'Debezium Connector',
      description:
        'Kafka Connect worker running Debezium; reads PostgreSQL WAL and publishes ' +
        'INSERT/UPDATE/DELETE events to Kafka topics.',
      stateful: true,
      image: 'debezium/connect:2.6',
      ports: [8083],
      dependsOn: ['kafka_broker'],
    },
    CLICKHOUSE_SINK,
  ],
  // ClickHouse connects directly to a PostgreSQL replication slot via the
  // MaterializedPostgreSQL engine — no message bus required (Req 3.1).
  materialized_engine: [
    CLICKHOUSE_SINK,
    {
      name: 'materialized_engine',
      displayName: 'Materialized Engine',
      description:
        'ClickHouse MaterializedPostgreSQL database engine that replicates directly from a ' +
        'PostgreSQL replication slot; runs inside the ClickHouse server.',
      stateful: true,
      dependsOn: ['clickhouse_sink'],
    },
  ],
  // Airbyte manages source/destination/connection via its own platform
  // (Req 4.1).
  airbyte: [
    {
      name: 'airbyte_connector',
      displayName: 'Airbyte Connector',
      description:
        'Airbyte platform that manages the PostgreSQL source, ClickHouse destination, and ' +
        'scheduled CDC connection.',
      stateful: true,
      image: 'airbyte/server:0.63.0',
      ports: [8001],
    },
    CLICKHOUSE_SINK,
  ],
};

/**
 * Lightweight edge components hosted by the `cloudflare_workers` target.
 * Identical across approaches — the Workers runtime only fronts the
 * stateful stack and runs the cache-invalidation logic, regardless of which
 * replication strategy the companion stateful deployment uses.
 */
const EDGE_SERVICES: readonly ServiceDefinition[] = [
  {
    name: 'cdc_api',
    displayName: 'CDC API / Control Plane',
    description:
      'Cloudflare Worker exposing the CDC control-plane endpoints; communicates with the ' +
      'stateful stack over HTTPS.',
    stateful: false,
  },
  {
    name: 'cache_invalidator',
    displayName: 'Cache Invalidator',
    description:
      'Cloudflare Worker that consumes CDC change events and refreshes Redis cache entries ' +
      '(INSERT/UPDATE → SET, DELETE → DEL).',
    stateful: false,
  },
];

// ── environment variable catalog ────────────────────────────────────────

/** Variables present in every deployment regardless of target. */
function universalVars(approach: CdcConnectorType, target: DeploymentTarget): EnvVarDefinition[] {
  return [
    {
      key: 'CDC_PIPELINE_NAME',
      description: 'Human-readable name of the CDC pipeline this deployment serves.',
      required: true,
      validation: { rule: 'Must be a non-empty string of at most 128 characters', min: 1, max: 128 },
    },
    {
      key: 'CDC_APPROACH',
      description: 'The CDC replication approach this deployment implements.',
      default: approach,
      required: true,
      validation: enumValidation(['debezium_kafka', 'materialized_engine', 'airbyte']),
    },
    {
      key: 'CDC_DEPLOYMENT_TARGET',
      description: 'The deployment target hosting these components.',
      default: target,
      required: true,
      validation: enumValidation(['docker_compose', 'cloudflare_workers']),
    },
  ];
}

/** Stateful-stack connection variables shared by all approaches. */
function statefulCommonVars(): EnvVarDefinition[] {
  return [
    {
      key: 'SOURCE_DATABASE_URL',
      description: 'PostgreSQL Source_Database connection string the connector replicates from.',
      required: true,
      validation: urlValidation(['postgres', 'postgresql']),
    },
    {
      key: 'CLICKHOUSE_SINK_URL',
      description: 'ClickHouse_Sink connection string that receives replicated data.',
      required: true,
      validation: urlValidation(['clickhouse', 'http', 'https']),
    },
    {
      key: 'CLICKHOUSE_DATABASE',
      description: 'ClickHouse database name that holds the replicated tables.',
      default: 'default',
      required: false,
      validation: NON_EMPTY,
    },
    {
      key: 'CDC_REPLICATION_TABLES',
      description: 'Comma-separated list of fully-qualified PostgreSQL tables to replicate.',
      required: true,
      validation: {
        rule: 'Comma-separated list of one or more fully-qualified table names',
        pattern: '^[^,]+(,[^,]+)*$',
      },
    },
  ];
}

/** Approach-specific stateful variables for the `docker_compose` target. */
function statefulApproachVars(approach: CdcConnectorType): EnvVarDefinition[] {
  switch (approach) {
    case 'debezium_kafka':
      return [
        {
          key: 'KAFKA_BOOTSTRAP_SERVERS',
          description: 'Comma-separated Kafka_Broker bootstrap servers (host:port).',
          default: 'kafka:9092',
          required: true,
          validation: {
            rule: 'Comma-separated list of host:port entries',
            pattern: '^[^,:]+:[0-9]+(,[^,:]+:[0-9]+)*$',
          },
        },
        {
          key: 'DEBEZIUM_CONNECT_URL',
          description: 'Debezium Kafka Connect REST endpoint used to register the connector.',
          default: 'http://debezium:8083',
          required: true,
          validation: urlValidation(['http', 'https']),
        },
        {
          key: 'KAFKA_TOPIC_PREFIX',
          description: 'Prefix applied to per-table Kafka topics created by Debezium.',
          default: 'lumibase_cdc',
          required: false,
          validation: NON_EMPTY,
        },
        {
          key: 'DEBEZIUM_SLOT_NAME',
          description: 'PostgreSQL replication slot name Debezium creates on the Source_Database.',
          default: 'lumibase_debezium',
          required: false,
          validation: NON_EMPTY,
        },
        {
          key: 'DEBEZIUM_PUBLICATION_NAME',
          description: 'PostgreSQL publication name Debezium uses for logical replication.',
          default: 'lumibase_cdc_pub',
          required: false,
          validation: NON_EMPTY,
        },
        {
          key: 'KAFKA_BUFFER_MAX_BYTES',
          description: 'Local buffer size cap (bytes) retained during a Kafka outage (Req 2.3).',
          default: '524288000',
          required: false,
          validation: positiveIntValidation(),
        },
        {
          key: 'KAFKA_BUFFER_MAX_AGE_MS',
          description: 'Maximum age (ms) of locally buffered events during a Kafka outage (Req 2.3).',
          default: '3600000',
          required: false,
          validation: positiveIntValidation(),
        },
        {
          key: 'DEBEZIUM_MAX_SLOT_FAILURES',
          description:
            'Consecutive replication-slot failures tolerated before the pipeline is marked ' +
            'error (Req 2.5).',
          default: '3',
          required: false,
          validation: positiveIntValidation(),
        },
      ];
    case 'materialized_engine':
      return [
        {
          key: 'MATERIALIZED_DATABASE_NAME',
          description: 'ClickHouse MaterializedPostgreSQL database name created for replication.',
          default: 'lumibase_cdc_mat',
          required: false,
          validation: NON_EMPTY,
        },
        {
          key: 'MATERIALIZED_SLOT_NAME',
          description: 'PostgreSQL replication slot name the Materialized Engine owns (Req 3.1).',
          default: 'lumibase_mat',
          required: false,
          validation: NON_EMPTY,
        },
        {
          key: 'MATERIALIZED_RECONNECT_MAX_RETRIES',
          description: 'Maximum reconnection attempts before erroring (Req 3.4).',
          default: '5',
          required: false,
          validation: positiveIntValidation(),
        },
        {
          key: 'MATERIALIZED_RECONNECT_BASE_DELAY_MS',
          description: 'Initial exponential-backoff delay (ms) for reconnection (Req 3.4).',
          default: '1000',
          required: false,
          validation: positiveIntValidation(),
        },
        {
          key: 'MATERIALIZED_SCHEMA_DRIFT_INTERVAL_MS',
          description: 'Interval (ms) at which source schema drift is checked (Req 3.6).',
          default: '60000',
          required: false,
          validation: positiveIntValidation(),
        },
      ];
    case 'airbyte':
      return [
        {
          key: 'AIRBYTE_API_URL',
          description: 'Airbyte_Connector API base URL used to provision source/destination/connection.',
          default: 'http://airbyte:8001/api',
          required: true,
          validation: urlValidation(['http', 'https']),
        },
        {
          key: 'AIRBYTE_WORKSPACE_ID',
          description: 'Airbyte workspace ID that owns the provisioned resources.',
          required: true,
          validation: NON_EMPTY,
        },
        {
          key: 'AIRBYTE_SYNC_MODE',
          description: 'Airbyte sync mode for the connection (Req 4.2).',
          default: 'incremental_cdc',
          required: false,
          validation: enumValidation(['full_refresh', 'incremental_cdc']),
        },
        {
          key: 'AIRBYTE_SYNC_INTERVAL_SECONDS',
          description:
            'Sync schedule interval in seconds; enforces the 5-minute Airbyte minimum ' +
            '(Req 4.3, 4.7).',
          default: '300',
          required: false,
          validation: intRangeValidation(300, 86400),
        },
        {
          key: 'AIRBYTE_PROVISION_TIMEOUT_MS',
          description: 'Timeout (ms) for provisioning Airbyte resources (Req 4.1).',
          default: '120000',
          required: false,
          validation: positiveIntValidation(),
        },
        {
          key: 'AIRBYTE_SYNC_MAX_RETRIES',
          description: 'Number of times a failed sync is retried with backoff (Req 4.4).',
          default: '3',
          required: false,
          validation: positiveIntValidation(),
        },
      ];
    default: {
      // Exhaustiveness guard — fails to compile if a new approach is added
      // without a corresponding env-var set.
      const _exhaustive: never = approach;
      return _exhaustive;
    }
  }
}

/**
 * Edge-component variables for the `cloudflare_workers` target. Identical
 * across approaches: the Workers runtime only fronts the stateful stack
 * (over HTTPS) and runs the Cache_Invalidator logic.
 */
function edgeVars(): EnvVarDefinition[] {
  return [
    {
      key: 'CDC_STATEFUL_STACK_URL',
      description:
        'HTTPS endpoint of the companion docker_compose/managed-services stateful deployment the ' +
        'Workers runtime communicates with.',
      required: true,
      validation: urlValidation(['https'], 'HTTPS required for the Workers runtime'),
    },
    {
      key: 'CDC_API_AUTH_TOKEN',
      description:
        'Bearer token securing the CDC control-plane API endpoints exposed by the Worker.',
      required: true,
      validation: NON_EMPTY,
    },
    {
      key: 'REDIS_URL',
      description: 'Redis connection string the Cache_Invalidator refreshes (Req 5.1).',
      required: true,
      validation: urlValidation(['redis', 'rediss']),
    },
    {
      key: 'CACHE_KEY_NAMESPACE',
      description: 'CacheProvider key namespace prefix used when deriving cache keys (Req 5.2).',
      default: 'lumibase',
      required: false,
      validation: NON_EMPTY,
    },
    {
      key: 'CACHE_INVALIDATOR_QUEUE_MAX',
      description: 'Bounded queue size for buffering events during a Redis outage (Req 5.5).',
      default: '10000',
      required: false,
      validation: positiveIntValidation(),
    },
    {
      key: 'CACHE_INVALIDATOR_DEDUP_WINDOW_MS',
      description:
        'Deduplication window (ms) for collapsing consecutive UPDATE events for the same key ' +
        '(Req 5.3).',
      default: '1000',
      required: false,
      validation: positiveIntValidation(),
    },
  ];
}

// ── public API ───────────────────────────────────────────────────────────

/**
 * Generate the complete {@link EnvironmentConfig} for a CDC `approach` and
 * deployment `target` (Req 7.1).
 *
 * The result is scoped by target (Req 7.2):
 *
 *   - **`docker_compose`** → the full stateful stack for the approach
 *     (connection variables + approach-specific tuning, and the
 *     Kafka/Debezium/ClickHouse/Materialized/Airbyte services relevant to
 *     the approach).
 *   - **`cloudflare_workers`** → edge components ONLY (the CDC
 *     API/control-plane and Cache_Invalidator, with their HTTPS/Redis
 *     variables). Stateful connectors, the message bus, and replication
 *     engines are explicitly excluded — those live in a companion
 *     `docker_compose`/managed-services deployment.
 *
 * Universal identity variables (`CDC_PIPELINE_NAME`, `CDC_APPROACH`,
 * `CDC_DEPLOYMENT_TARGET`) are always present so both halves of a split
 * deployment can be correlated.
 *
 * The function is pure and total: every valid `(approach, target)` pair
 * yields a config whose required variables are all present, satisfying
 * Property 17 (task 11.5).
 *
 * @param approach - The CDC replication strategy.
 * @param target - Where the components run.
 * @returns The deployment configuration for this combination.
 */
export function generateConfig(
  approach: CdcConnectorType,
  target: DeploymentTarget,
): EnvironmentConfig {
  const variables: EnvVarDefinition[] = [...universalVars(approach, target)];
  let services: readonly ServiceDefinition[];

  if (target === 'docker_compose') {
    // Full stateful stack for the approach.
    variables.push(...statefulCommonVars(), ...statefulApproachVars(approach));
    services = STATEFUL_SERVICES_BY_APPROACH[approach];
  } else {
    // Edge components only — exclude stateful connectors, the message bus,
    // and replication engines (Req 7.2).
    variables.push(...edgeVars());
    services = EDGE_SERVICES;
  }

  return { approach, target, variables, services };
}

/**
 * Convenience helper returning the keys of every **required** variable in a
 * generated config, in declaration order. Useful for completeness checks
 * (Property 17) and documentation.
 *
 * @param config - A config produced by {@link generateConfig}.
 * @returns The required variable keys.
 */
export function requiredEnvVarKeys(config: EnvironmentConfig): string[] {
  return config.variables.filter((v) => v.required).map((v) => v.key);
}
