import { index, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';
import { nanoid } from 'nanoid';
import { sites, users } from './core';

/**
 * Content OS tables: declared desired state (SLO) for content.
 * `content_intents` drives the reconciliation loop — drift detectors scan
 * collections against intent rules and the reconciler turns drift into
 * agent goals executed under the intent's autonomy cap and budget.
 */

const id = () => text('id').$defaultFn(() => nanoid()).primaryKey();
const createdAt = () => timestamp('created_at').defaultNow().notNull();
const updatedAt = () => timestamp('updated_at').defaultNow().notNull();

export const contentIntents = pgTable(
  'content_intents',
  {
    id: id(),
    siteId: text('site_id')
      .notNull()
      .references(() => sites.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    /** Target collection the intent governs. */
    collection: text('collection').notNull(),
    /** Declarative rule list validated against the intent-rule.v1 schema. */
    rules: jsonb('rules').default([]).notNull(),
    /** Cron expression driving drift scans. */
    schedule: text('schedule').notNull(),
    /** { maxGoalsPerCycle, maxWritesPerMinute, maxCostUsd } */
    budget: jsonb('budget').default({}).notNull(),
    /** Autonomy ceiling (0-4) for goals generated by this intent. */
    autonomyCap: integer('autonomy_cap').default(2).notNull(),
    /** { tz, windows: [{ dow, start, end }] } — null means always allowed. */
    maintenanceWindow: jsonb('maintenance_window'),
    /** `active` | `paused` | `error` */
    status: text('status').default('active').notNull(),
    /** Why the intent is in `error` (circuit breaker detail). */
    statusReason: text('status_reason'),
    createdBy: text('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => ({
    siteNameUnique: uniqueIndex('content_intents_site_name_unique').on(t.siteId, t.name),
    siteStatusIdx: index('content_intents_site_status_idx').on(t.siteId, t.status),
    siteCollectionIdx: index('content_intents_site_collection_idx').on(t.siteId, t.collection),
  }),
);
