// Generated by `lumibase types` — do not edit by hand.
// Re-run the command after changing collections or fields.

import type { ID, Locale } from 'lumibase';
import type { Brand } from 'lumibase';

export interface Posts {
  readonly id: Brand<'PostsId', string>;
  status: string;
  sort: number;
  readonly user_created?: string | null;
  readonly user_updated?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
  readonly deleted_at?: string | null;
  author?: string | null;
  body?: string | null;
  title: string | null;
}

export type PostsExpanded = Posts;

export interface LumibaseCollections {
  posts: Posts;
}

export type LumibaseSchema = LumibaseCollections;
