#!/usr/bin/env node
/**
 * lumibase typegen — fetch the manifest from a running CMS instance and
 * emit a TypeScript types file usable by client apps (Next.js, etc.).
 *
 * Usage:
 *   pnpm lumibase typegen \
 *     --site <siteId> \
 *     --out ./apps/web/src/lumibase-types.ts \
 *     --url http://localhost:8787 \
 *     --auth $LUMI_TOKEN \
 *     [--include posts,tags] [--exclude users] [--format single|per-collection]
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { generateTypes } from '@lumibase/sdk';
import type { TypegenManifest } from '@lumibase/sdk';

interface CliArgs {
  site: string;
  out: string;
  url: string;
  auth?: string;
  include?: string;
  exclude?: string;
  format: 'single' | 'per-collection';
  branded: boolean;
}

function parseArgs(argv: string[]): CliArgs {
  const args: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg.startsWith('--')) {
      const key = arg.slice(2);
      const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[++i] : 'true';
      args[key] = value;
    }
  }

  const site = args.site || process.env.LUMI_SITE || '';
  const out = args.out || './lumibase-types.ts';
  const url = args.url || process.env.LUMI_URL || 'http://localhost:8787';
  const auth = args.auth || process.env.LUMI_TOKEN;

  if (!site) {
    console.error('Error: --site <siteId> is required (or set LUMI_SITE env var).');
    process.exit(1);
  }

  return {
    site,
    out,
    url,
    auth,
    include: args.include,
    exclude: args.exclude,
    format: (args.format as 'single' | 'per-collection') || 'single',
    branded: args.branded !== 'false',
  };
}

async function fetchManifest(args: CliArgs): Promise<TypegenManifest> {
  const url = new URL('/api/v1/typegen/schema', args.url);
  if (args.include) url.searchParams.set('include', args.include);
  if (args.exclude) url.searchParams.set('exclude', args.exclude);

  const res = await fetch(url, {
    headers: {
      'X-Lumi-Site': args.site,
      ...(args.auth ? { Authorization: `Bearer ${args.auth}` } : {}),
    },
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch manifest: ${res.status} ${res.statusText}`);
  }

  const body = (await res.json()) as { data: TypegenManifest };
  return body.data;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  console.log(`[typegen] Fetching manifest from ${args.url} for site ${args.site}...`);

  const manifest = await fetchManifest(args);
  console.log(`[typegen] Got ${manifest.collections.length} collections.`);

  const code = generateTypes(manifest, { format: args.format, branded: args.branded });

  const header = `/* eslint-disable */\n// AUTO-GENERATED by \`lumibase typegen\` — DO NOT EDIT.\n// Site: ${manifest.site}\n// Generated: ${new Date().toISOString()}\n\n`;

  const outPath = resolve(process.cwd(), args.out);
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, header + code, 'utf8');

  console.log(`[typegen] Wrote ${outPath}`);
}

main().catch((err) => {
  console.error('[typegen] FAILED:', err);
  process.exit(1);
});
