-- Snapshot-baseline realignment (no-op migration).
--
-- The committed drizzle snapshots had drifted: they stopped at `0011`
-- (48 tables) while migrations `0012`–`0035` were authored by hand and
-- never refreshed the snapshot. As a result `drizzle-kit generate` diffed
-- the live schema (78 tables) against the stale baseline and tried to
-- re-`CREATE` every already-existing table on each run.
--
-- This migration carries an accurate full-schema snapshot
-- (`meta/0036_snapshot.json`) so future `generate` runs diff against
-- reality and emit only genuine changes. It intentionally executes NO DDL:
-- every table the snapshot describes was already created by migrations
-- `0012`–`0035`, which run before this one on both fresh and existing
-- databases. Applying CREATE statements here would fail on existing DBs.
SELECT 1;
